import PDFDocument from "pdfkit";

export interface DocumentSection {
  heading: string;
  content_markdown: string;
}

export interface DocumentSource {
  title: string;
  url: string;
}

export interface DocumentRequest {
  type: "pdf" | "docx";
  title: string;
  filename: string;
  sections: DocumentSection[];
  tables?: {
    title: string;
    columns: string[];
    rows: string[][];
  }[];
  sources?: DocumentSource[];
}

export async function generatePDF(request: DocumentRequest): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
      size: "A4",
      info: {
        Title: request.title,
        Author: "Aura AI",
        Creator: "Aura — Truth-First AI Thinking Partner",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text(request.title, { align: "center" });

    doc
      .moveDown(0.3)
      .fontSize(9)
      .font("Helvetica")
      .fillColor("#888888")
      .text(`Generated by Aura — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, { align: "center" });

    doc.moveDown(1.5).fillColor("#000000");

    for (const section of request.sections) {
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text(section.heading);

      doc.moveDown(0.4);

      const lines = section.content_markdown.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.3);
          continue;
        }

        const bulletMatch = trimmed.match(/^[→\-*•]\s*(.*)/);
        const numberedMatch = trimmed.match(/^(\d+)\.\s*(.*)/);

        if (bulletMatch) {
          renderRichLine(doc, `  →  ${bulletMatch[1]}`, 10);
        } else if (numberedMatch) {
          renderRichLine(doc, `  ${numberedMatch[1]}.  ${numberedMatch[2]}`, 10);
        } else {
          renderRichLine(doc, trimmed, 10);
        }
        doc.moveDown(0.15);
      }

      doc.moveDown(0.8);
    }

    if (request.tables && request.tables.length > 0) {
      for (const table of request.tables) {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text(table.title);
        doc.moveDown(0.4);

        const colWidth = (doc.page.width - 100) / table.columns.length;

        doc.fontSize(9).font("Helvetica-Bold");
        table.columns.forEach((col, i) => {
          doc.text(col, 50 + i * colWidth, doc.y, {
            width: colWidth,
            continued: i < table.columns.length - 1,
          });
        });
        doc.moveDown(0.3);

        const lineY = doc.y;
        doc
          .moveTo(50, lineY)
          .lineTo(doc.page.width - 50, lineY)
          .strokeColor("#cccccc")
          .stroke();
        doc.moveDown(0.3);

        doc.fontSize(9).font("Helvetica");
        for (const row of table.rows) {
          const startY = doc.y;
          row.forEach((cell, i) => {
            doc.text(cell, 50 + i * colWidth, startY, {
              width: colWidth,
            });
          });
          doc.moveDown(0.2);
        }

        doc.moveDown(0.8);
      }
    }

    if (request.sources && request.sources.length > 0) {
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Sources");
      doc.moveDown(0.4);

      for (const source of request.sources) {
        doc
          .fontSize(9)
          .font("Helvetica")
          .fillColor("#3B82F6")
          .text(`→  ${source.title}`, { link: source.url, underline: true });
        doc
          .fontSize(8)
          .fillColor("#888888")
          .text(`   ${source.url}`);
        doc.moveDown(0.2);
      }

      doc.fillColor("#000000");
    }

    doc.end();
  });
}

function renderRichLine(doc: PDFKit.PDFDocument, text: string, fontSize: number) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);

  let first = true;
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      doc.fontSize(fontSize).font("Helvetica-Bold");
      doc.text(part.slice(2, -2), { continued: true });
    } else if (part) {
      doc.fontSize(fontSize).font("Helvetica");
      if (first) {
        doc.text(part, { continued: true });
      } else {
        doc.text(part, { continued: true });
      }
    }
    first = false;
  }

  doc.text("", { continued: false });
}
